# Generated by Django 4.1 on 2022-12-20 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tintit', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(auto_created=True, default=0)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField(blank=True, max_length=160)),
                ('file_img', models.ImageField(blank=True, upload_to='static/tintit/wallpapers')),
                ('url_img', models.TextField(blank=True)),
                ('allow_comments', models.BooleanField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
